name: Development
on: [pull_request]
jobs: 
  test: 
    name: Landing page test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v2

      - name: "setup node"
        uses: actions/setup-node@v2.1.5
        with: 
          node-version: 16

      - name: "install npm@latest"
        run: npm i -g npm@latest

      - name: "install dependencies"
        uses: bahmutov/npm-install@v1

      - name: "Run tests"
        run: npm run test  --if-present